// Все пути под /factorial (модуль смонтирован в Энцеладусе как /factorial/*).
export const ROUTES = {
  dashboard: '/factorial',
  inbox: '/factorial/inbox',
  inboxTodo: '/factorial/inbox/todo',
  inboxCompleted: '/factorial/inbox/completed',
  calendar: '/factorial/calendar',
  calendarTeam: '/factorial/calendar/team-view',
  discover: '/factorial/discover',
  profile: '/factorial/profile',
  profileWorkDetails: '/factorial/profile/work-details',
  profilePersonal: '/factorial/profile/personal',
  profileContracts: '/factorial/profile/contract_versions',
  profilePlanning: '/factorial/profile/planning_versions',
  profileCustom: '/factorial/profile/custom_tables',
  timeOff: '/factorial/time-off',
  tasks: '/factorial/tasks',
  myDocuments: '/factorial/my-documents',
  employees: '/factorial/employees',
  employeesTeams: '/factorial/employees/teams',
  employeesOrgChart: '/factorial/employees/org-chart',
  employeesVacancies: '/factorial/employees/vacancies',
  files: '/factorial/files',
  pages: '/factorial/pages',
  ticketing: '/factorial/ticketing',
  talentAnalytics: '/factorial/talent_analytics',
  analytics: '/factorial/analytics',
  analyticsAdvanced: '/factorial/analytics/reports/dashboards/list',
  analyticsInsights: '/factorial/analytics/insights',
  workflows: '/factorial/workflows',
  workflowsSurveys: '/factorial/workflows/surveys',
  workflowsOnboarding: '/factorial/workflows/onboarding',
  workflowsOffboarding: '/factorial/workflows/offboarding',
  workflowsCustom: '/factorial/workflows/custom',
  settings: '/factorial/settings',
} as const;
