// Timing constants
export const TIMINGS = {
  API_TIMEOUT_MS: 30000,
  TOAST_DURATION_MS: 2000,
  TOUR_START_DELAY_MS: 100,
  FEATURE_POLL_INTERVAL_MS: 30000,
  MUTATION_DEBOUNCE_MS: 300,
  WS_RECONNECT_DELAY_MS: 3000,
  STALE_TIME_MS: 30000,
} as const;

// Limits
export const LIMITS = {
  MAX_SEARCH_HISTORY: 10,
  MAX_COMMAND_HISTORY: 10,
  SEARCH_CACHE_TTL_MS: 5 * 60 * 1000,
  MAX_FILE_SIZE_MB: 100,
} as const;

// UI
export const UI = {
  FOCUS_TIMEOUT_MS: 50,
  POSITION_UPDATE_DELAY_MS: 100,
  ANIMATION_STAGGER_MS: 100,
} as const;
