import { describe, it, expect } from "vitest";
import type { KanbanCard, KanbanColumn } from "@/services/api/candidates";
import type { EntityFile } from "@/services/api/entities";
import {
  isRejectedStage,
  resolveContainerStatusLabel,
  isAutoGeneratedFile,
  buildResumeSources,
  buildStageContainers,
  matchesTimelineFilter,
  CANDIDATE_VACANCY_STAGE_LABELS,
  readSystemHrTags,
} from "../model";

// ── Fixtures ──────────────────────────────────────────────────────────────
const file = (p: Partial<EntityFile>): EntityFile =>
  ({
    id: 1,
    file_name: "resume.pdf",
    mime_type: "application/pdf",
    file_type: "resume",
    created_at: "2026-01-01T00:00:00Z",
    ...p,
  }) as EntityFile;

const card = (p: Partial<KanbanCard> & { extra_data?: Record<string, unknown> }): KanbanCard =>
  ({
    id: 1,
    name: "Иван Петров",
    created_at: "2026-06-01T00:00:00Z",
    status: "applied",
    extra_data: {},
    ...p,
  }) as unknown as KanbanCard;

// ── isRejectedStage ────────────────────────────────────────────────────────
describe("isRejectedStage", () => {
  it("true for rejected/fired/archived", () => {
    expect(isRejectedStage("rejected")).toBe(true);
    expect(isRejectedStage("fired")).toBe(true);
    expect(isRejectedStage("archived")).toBe(true);
  });
  it("false for active stages", () => {
    expect(isRejectedStage("applied")).toBe(false);
    expect(isRejectedStage("interview")).toBe(false);
    expect(isRejectedStage("")).toBe(false);
  });
});

// ── resolveContainerStatusLabel ────────────────────────────────────────────
describe("resolveContainerStatusLabel", () => {
  const cols = (s: string, label: string): KanbanColumn[] =>
    [{ status: s, label }] as unknown as KanbanColumn[];

  it("column override wins over everything", () => {
    expect(resolveContainerStatusLabel("applied", cols("applied", "Мой этап"))).toBe(
      "Мой этап",
    );
  });
  it("falls back to the raw status for a fully unknown key", () => {
    expect(resolveContainerStatusLabel("zzz_unknown_stage", [])).toBe(
      "zzz_unknown_stage",
    );
  });
  it("uses the canonical vacancy labels as a fallback", () => {
    // 'reserve' is not a column here; with no STATUS_LABELS entry it lands on
    // the local canon. (If STATUS_LABELS also defines it, that wins — both are
    // human labels, never the raw key.)
    const label = resolveContainerStatusLabel("reserve", []);
    expect(label).not.toBe("reserve");
    expect(CANDIDATE_VACANCY_STAGE_LABELS.reserve).toBe("Резерв");
  });
});

// ── isAutoGeneratedFile ────────────────────────────────────────────────────
describe("isAutoGeneratedFile", () => {
  it("flags per-page résumé scans (images)", () => {
    expect(isAutoGeneratedFile(file({ file_name: "Резюме стр. 1.jpg", mime_type: "image/jpeg" }))).toBe(true);
    expect(isAutoGeneratedFile(file({ file_name: "Профиль_Титов_Семён_стр1.jpg", mime_type: "image/jpeg" }))).toBe(true);
    expect(isAutoGeneratedFile(file({ file_name: "x_cv_page.png", mime_type: "image/png" }))).toBe(true);
    expect(isAutoGeneratedFile(file({ file_name: "doc_page.jpg", mime_type: "image/jpeg" }))).toBe(true);
  });
  it("flags auto-extracted avatar photos regardless of mime", () => {
    expect(isAutoGeneratedFile(file({ file_name: "Фото_Иван.jpg", mime_type: "image/jpeg" }))).toBe(true);
    expect(isAutoGeneratedFile(file({ file_name: "Фото_Иван.pdf", mime_type: "application/pdf" }))).toBe(true);
  });
  it("does NOT flag the page-pattern on non-images", () => {
    // "стр." pattern only counts for images — a PDF named so is a real doc.
    expect(isAutoGeneratedFile(file({ file_name: "Резюме стр. 1.pdf", mime_type: "application/pdf" }))).toBe(false);
  });
  it("does NOT flag normal files", () => {
    expect(isAutoGeneratedFile(file({ file_name: "resume.pdf", mime_type: "application/pdf" }))).toBe(false);
    expect(isAutoGeneratedFile(file({ file_name: "selfie.jpg", mime_type: "image/jpeg" }))).toBe(false);
    expect(isAutoGeneratedFile(file({ file_name: "", mime_type: "image/jpeg" }))).toBe(false);
  });
});

// ── buildResumeSources ─────────────────────────────────────────────────────
describe("buildResumeSources", () => {
  it("empty when no files and no demos", () => {
    expect(buildResumeSources([], {})).toEqual([]);
    expect(buildResumeSources([], undefined)).toEqual([]);
  });
  it("parsed source from extra_data.resume_demo (single) and resume_demos (array)", () => {
    expect(buildResumeSources([], { resume_demo: { title: "x" } })).toEqual([{ kind: "parsed" }]);
    expect(buildResumeSources([], { resume_demos: [{ title: "x" }] })).toEqual([{ kind: "parsed" }]);
  });
  it("one pdf source per résumé PDF, newest first", () => {
    const f1 = file({ id: 1, mime_type: "application/pdf", created_at: "2026-01-01T00:00:00Z" });
    const f2 = file({ id: 2, mime_type: "application/pdf", created_at: "2026-05-01T00:00:00Z" });
    const out = buildResumeSources([f1, f2], {});
    expect(out).toEqual([
      { kind: "pdf", file: f2 },
      { kind: "pdf", file: f1 },
    ]);
  });
  it("parsed + pdf together", () => {
    const f1 = file({ id: 1, mime_type: "application/pdf" });
    expect(buildResumeSources([f1], { resume_demo: { title: "x" } })).toEqual([
      { kind: "parsed" },
      { kind: "pdf", file: f1 },
    ]);
  });
  it("images source ONLY when no parsed and no pdf", () => {
    const img = file({ id: 3, mime_type: "image/jpeg" });
    expect(buildResumeSources([img], {})).toEqual([{ kind: "images" }]);
  });
  it("images suppressed when a pdf or parsed exists", () => {
    const img = file({ id: 3, mime_type: "image/jpeg" });
    const pdf = file({ id: 1, mime_type: "application/pdf" });
    expect(buildResumeSources([img, pdf], {})).toEqual([{ kind: "pdf", file: pdf }]);
    expect(buildResumeSources([img], { resume_demo: { title: "x" } })).toEqual([{ kind: "parsed" }]);
  });
  it("ignores files whose file_type is not 'resume'", () => {
    const other = file({ id: 9, mime_type: "application/pdf", file_type: "document" });
    expect(buildResumeSources([other], {})).toEqual([]);
  });
});

// ── buildStageContainers ───────────────────────────────────────────────────
describe("buildStageContainers", () => {
  const base = {
    status: "applied",
    liveApplicationId: 100,
    liveEvents: undefined,
    liveVacancyTitle: "Frontend",
    allEntityFiles: [] as EntityFile[],
  };

  it("returns only the live container when there is no merged_from", () => {
    const out = buildStageContainers({
      ...base,
      card: card({ name: "Иван", created_at: "2026-06-01T00:00:00Z", extra_data: { notes: [{ id: "n1", text: "hi" }] } }),
    });
    expect(out).toHaveLength(1);
    expect(out[0]).toMatchObject({
      origin: "live",
      applicationId: 100,
      status: "applied",
      name: "Иван",
      vacancyTitle: "Frontend",
      addedAt: "2026-06-01T00:00:00Z",
    });
    expect(out[0].notes).toEqual([{ id: "n1", text: "hi" }]);
  });

  it("appends one merged container per merged_from entry, with defaults", () => {
    const out = buildStageContainers({
      ...base,
      card: card({
        extra_data: {
          merged_from: [
            { status: "rejected", name: "Ivan P", vacancy_title: "Backend", added_at: "2026-05-01", file_ids: [7], extra_data: { notes: [{ id: "m1", text: "rej" }] } },
            // missing fields → defaults; note keeps it from being pruned as «empty»
            { extra_data: { notes: [{ id: "m2", text: "x" }] } },
          ],
        },
      }),
    });
    expect(out).toHaveLength(3); // live + 2 merged
    expect(out[1]).toMatchObject({
      origin: "merged",
      applicationId: -1,
      status: "rejected",
      name: "Ivan P",
      vacancyTitle: "Backend",
      addedAt: "2026-05-01",
      fileIds: [7],
    });
    expect(out[1].notes).toEqual([{ id: "m1", text: "rej" }]);
    // defaults for the empty entry
    expect(out[2]).toMatchObject({ origin: "merged", applicationId: -2, status: "new", name: null, vacancyTitle: null, fileIds: [] });
  });

  it("subtracts notes already shown in merged containers from the live one (dedup)", () => {
    const out = buildStageContainers({
      ...base,
      card: card({
        extra_data: {
          notes: [
            { id: "shared", text: "dup" }, // also in merged → removed from live
            { id: "own", text: "mine" }, // stays on live
          ],
          merged_from: [{ extra_data: { notes: [{ id: "shared", text: "dup" }] } }],
        },
      }),
    });
    expect(out[0].notes).toEqual([{ id: "own", text: "mine" }]);
    expect(out[1].notes).toEqual([{ id: "shared", text: "dup" }]);
  });

  it("dedups notes without id by text+date signature", () => {
    const out = buildStageContainers({
      ...base,
      card: card({
        extra_data: {
          notes: [{ text: "hi", date: "d1" }, { text: "keep", date: "d2" }],
          merged_from: [{ extra_data: { notes: [{ text: "hi", date: "d1" }] } }],
        },
      }),
    });
    expect(out[0].notes).toEqual([{ text: "keep", date: "d2" }]);
  });

  it("partitions files: merged gets its file_ids, live gets the rest, auto-files excluded", () => {
    const ownDoc = file({ id: 1, mime_type: "application/pdf", file_name: "cv.pdf" });
    const mergedDoc = file({ id: 7, mime_type: "application/pdf", file_name: "old.pdf" });
    const autoScan = file({ id: 9, mime_type: "image/jpeg", file_name: "Резюме стр. 1.jpg" });
    const out = buildStageContainers({
      ...base,
      allEntityFiles: [ownDoc, mergedDoc, autoScan],
      card: card({ extra_data: { merged_from: [{ file_ids: [7] }] } }),
    });
    // live = own docs minus merged minus auto
    expect(out[0].files).toEqual([ownDoc]);
    // merged = its file_ids (auto-file id 9 not among them)
    expect(out[1].files).toEqual([mergedDoc]);
  });

  it("dedups the same physical file across containers (same name+type shown once)", () => {
    // Один и тот же документ прилетел от двух дублей как разные строки (id 7 и 8).
    const live = file({ id: 1, mime_type: "application/pdf", file_name: "cv.pdf" });
    const dupA = file({ id: 7, mime_type: "application/pdf", file_name: "resume.pdf" });
    const dupB = file({ id: 8, mime_type: "application/pdf", file_name: "resume.pdf" });
    const out = buildStageContainers({
      ...base,
      allEntityFiles: [live, dupA, dupB],
      card: card({
        extra_data: {
          merged_from: [{ file_ids: [7] }, { file_ids: [8] }],
        },
      }),
    });
    // первый влитой забирает resume.pdf; второй получает пустую копию (дедуп срабатывает)
    // но оба контейнера остаются, потому что показываем ВСЕ merged профили
    expect(out).toHaveLength(3); // live + 2 merged (оба остаются)
    expect(out[1].files).toEqual([dupA]); // первый имеет файл
    expect(out[2].files).toEqual([]); // второй пустой (дедуп)
    expect(out[0].files).toEqual([live]);
  });
});

// ── matchesTimelineFilter ──────────────────────────────────────────────────
describe("matchesTimelineFilter", () => {
  it("matches «Комментарий» / «Смена этапа подбора» by kind, not text", () => {
    expect(matchesTimelineFilter({ kind: "comment", title: "что-то" }, "Комментарий")).toBe(true);
    expect(matchesTimelineFilter({ kind: "stage", title: "что-то" }, "Комментарий")).toBe(false);
    expect(matchesTimelineFilter({ kind: "stage", title: "Новый → Отказ" }, "Смена этапа подбора")).toBe(true);
    expect(matchesTimelineFilter({ kind: "comment", title: "x" }, "Смена этапа подбора")).toBe(false);
  });
  it("matches other filters by text aliases in title/body", () => {
    expect(matchesTimelineFilter({ kind: "stage", title: "Этап: Отказ" }, "Отказ")).toBe(true);
    expect(matchesTimelineFilter({ kind: "comment", body: "отправил email кандидату" }, "Письмо кандидату")).toBe(true);
    expect(matchesTimelineFilter({ kind: "comment", body: "телефонный разговор" }, "Телефонный звонок")).toBe(true);
  });
  it("returns false when nothing matches", () => {
    expect(matchesTimelineFilter({ kind: "comment", title: "обычный текст" }, "Оффер")).toBe(false);
  });
});

// ── readSystemHrTags ───────────────────────────────────────────────────────
describe("readSystemHrTags", () => {
  it("returns [] for missing / non-array / nullish extra_data", () => {
    expect(readSystemHrTags(undefined)).toEqual([]);
    expect(readSystemHrTags(null)).toEqual([]);
    expect(readSystemHrTags({})).toEqual([]);
    expect(readSystemHrTags({ system_hr_tags: "nope" })).toEqual([]);
    expect(readSystemHrTags({ system_hr_tags: {} })).toEqual([]);
  });
  it("reads well-formed HR tags preserving backend order", () => {
    expect(
      readSystemHrTags({
        system_hr_tags: [
          { hr_id: 7, name: "Мария" },
          { hr_id: 3, name: "Настя" },
        ],
      }),
    ).toEqual([
      { hr_id: 7, name: "Мария" },
      { hr_id: 3, name: "Настя" },
    ]);
  });
  it("drops malformed entries (missing/blank name, non-numeric id, null)", () => {
    expect(
      readSystemHrTags({
        system_hr_tags: [
          { hr_id: 1, name: "Оля" },
          { hr_id: "2", name: "Bad id" },
          { hr_id: 3, name: "   " },
          { hr_id: 4 },
          null,
          { name: "no id" },
        ],
      }),
    ).toEqual([{ hr_id: 1, name: "Оля" }]);
  });
  it("does not leak unknown keys — keeps only hr_id/name/vacancy fields", () => {
    expect(
      readSystemHrTags({
        system_hr_tags: [{ hr_id: 5, name: "Лена", extra: "x" }],
      }),
    ).toEqual([{ hr_id: 5, name: "Лена" }]);
  });
  it("keeps vacancy_id/vacancy_title when present, trims title", () => {
    expect(
      readSystemHrTags({
        system_hr_tags: [
          { hr_id: 7, name: "Ильнар", vacancy_id: 3, vacancy_title: " tesy ", junk: 1 },
        ],
      }),
    ).toEqual([{ hr_id: 7, name: "Ильнар", vacancy_id: 3, vacancy_title: "tesy" }]);
  });
  it("omits vacancy fields when absent, blank, or wrong type (legacy data)", () => {
    expect(
      readSystemHrTags({
        system_hr_tags: [
          { hr_id: 1, name: "Оля", vacancy_title: "   " },
          { hr_id: 2, name: "Настя", vacancy_id: "3" },
        ],
      }),
    ).toEqual([
      { hr_id: 1, name: "Оля" },
      { hr_id: 2, name: "Настя" },
    ]);
  });
});
