// ================================================================
// CandidateDetail — pure domain model for the candidate detail panel.
//
// Extracted VERBATIM from AllCandidatesPage's InfoTab so the panel can be
// reused (funnel + «Все кандидаты») WITHOUT forking behaviour. These are the
// "key methods": container/history assembly, note dedup, file classification,
// résumé-source derivation, stage-label resolution. They are PURE (no React,
// no I/O) and unit-tested in ./__tests__/model.test.ts — the safety net that
// guards the upcoming component extraction (zero-regression requirement).
// ================================================================
import type { KanbanCard, KanbanColumn } from "@/services/api/candidates";
import type { ActivityEvent, EntityFile } from "@/services/api/entities";
import { STATUS_LABELS } from "@/types";

// ── Types (moved from AllCandidatesPage — the panel's domain shapes) ──

export type DetailSection = "info" | "resume" | "anketa";

/** Комментарий (лог) одного контейнера. */
export type ContainerNote = {
  id?: string;
  text?: string;
  date?: string;
  stage?: string;
  stage_label?: string;
  author_id?: number;
  author_name?: string;
  edited_at?: string;
};

/** Резюме-демо одного контейнера (минимально нужные поля). */
export type ContainerResumeDemo = {
  title?: string;
  subtitle?: string;
  saved_at?: string;
  vacancy_title?: string;
};

/**
 * «Контейнер» = исторический блок-статус с собственным логом. Стек кандидата =
 * [ собственный живой контейнер ] + card.extra_data.merged_from[]. Это НЕ
 * вакансии: каждый контейнер изолирован своим status (цвет/лейбл) и notes (лог).
 */
export type StageContainer = {
  origin: "live" | "merged";
  applicationId: number;
  status: string;
  name: string | null;
  notes: ContainerNote[];
  resumeDemos: ContainerResumeDemo[];
  vacancyTitle: string | null;
  addedAt?: string;
  events?: ActivityEvent[];
  fileIds?: number[];
  files?: EntityFile[];
};

export type ResumeSource =
  | { kind: "parsed" }
  | { kind: "pdf"; file: EntityFile }
  | { kind: "images" };

export type ResumeDemoData = {
  title?: string;
  subtitle?: string;
  salary?: string;
  saved_at?: string;
  vacancy_title?: string;
  sections?: Array<{ title: string; lines: string[] }>;
};

// ── Stage status helpers ──

/** Этапы, при которых карточка остаётся нейтрально-серой (не «в процессе»). */
export const NEUTRAL_STAGE_STATUSES = new Set([
  "rejected",
  "fired",
  "archived",
]);

/** Этап считается «отклонённым» (серая карточка даже когда она единственная). */
export const isRejectedStage = (stage: string): boolean =>
  NEUTRAL_STAGE_STATUSES.has(stage);

/** Единые лейблы стадий карточки вакансии (совпадают с воронкой/бэкендом). */
export const CANDIDATE_VACANCY_STAGE_LABELS: Record<string, string> = {
  applied: "Новый",
  screening: "Выполняет ТЗ",
  phone_screen: "Интервью с HR",
  interview: "Интервью с заказчиком",
  assessment: "Принятие решения",
  offer: "Выставлен оффер",
  hired: "Оффер принят",
  probation: "Практика",
  transferred: "Перешёл в отдел",
  rejected: "Отказ",
  withdrawn: "Отозван",
  reserve: "Резерв",
};

/**
 * Лейбл статуса контейнера (EntityStatus → русский). Приоритет: org-override из
 * колонок доски → канон STATUS_LABELS → локальный CANDIDATE_VACANCY_STAGE_LABELS
 * → сам ключ.
 */
export function resolveContainerStatusLabel(
  status: string,
  columns: KanbanColumn[],
): string {
  const col = columns.find((c) => c.status === status);
  return (
    col?.label ||
    (STATUS_LABELS as Record<string, string>)[status] ||
    CANDIDATE_VACANCY_STAGE_LABELS[status] ||
    status
  );
}

// ── File classification ──

/**
 * Авто-файл = постраничный скан резюме у КАРТИНКИ («…стр. N…», «cv_page»,
 * «_page») ИЛИ авто-извлечённое фото-аватар («Фото_…»). Такие файлы — это
 * рендеры/аватар, а не вложения, и в список «Файлы» не идут.
 */
export function isAutoGeneratedFile(file: EntityFile): boolean {
  const name = file.file_name || "";
  const isImage = (file.mime_type || "").startsWith("image/");
  return (
    (isImage && /стр\.?\s*\d|cv_page|_page\b/i.test(name)) ||
    /^Фото_/i.test(name)
  );
}

// ── Résumé sources (pure part of useResumeSources) ──

/**
 * Из файлов кандидата + extra_data собирает список вкладок «Резюме»:
 * [распарсенное] + [каждый PDF, новое сверху] + [сканы-картинки — ТОЛЬКО если
 * другого резюме нет, иначе это дубль].
 */
export function buildResumeSources(
  files: EntityFile[],
  extraData: Record<string, unknown> | undefined,
): ResumeSource[] {
  const resumeFiles = files.filter((f) => f.file_type === "resume");
  const pdfFiles = resumeFiles
    .filter((f) => f.mime_type === "application/pdf")
    .sort((a, b) => (b.created_at || "").localeCompare(a.created_at || ""));
  const imageFiles = resumeFiles.filter((f) =>
    f.mime_type?.startsWith("image/"),
  );
  const resumeDemo = extraData?.resume_demo as ResumeDemoData | undefined;
  const resumeDemos = (
    Array.isArray(extraData?.resume_demos)
      ? (extraData?.resume_demos as ResumeDemoData[])
      : resumeDemo
        ? [resumeDemo]
        : []
  ).filter(Boolean);

  return [
    ...(resumeDemos.length > 0 ? [{ kind: "parsed" as const }] : []),
    ...pdfFiles.map((file) => ({ kind: "pdf" as const, file })),
    ...(imageFiles.length > 0 &&
    resumeDemos.length === 0 &&
    pdfFiles.length === 0
      ? [{ kind: "images" as const }]
      : []),
  ];
}

// ── Stage containers (pure part of the `containers` useMemo) ──

/**
 * Собирает стек контейнеров кандидата: [ собственный живой ] + merged_from[].
 * Живой контейнер — из самого кандидата (card); merged — плоский массив влитых
 * дублей (транзитивные слияния уже подняты в корень бэкендом). Заметки источника
 * вычитаются из живого (flat-merge на бэкенде их задваивает). Авто-файлы
 * (постраничные сканы / фото-аватар) исключаются из списков файлов контейнеров.
 *
 * `liveApplicationId` / `liveEvents` / `liveVacancyTitle` вычисляет вызывающая
 * сторона (primaryBlock + getVacancyStageLabel) — модель остаётся чистой.
 */
export function buildStageContainers(params: {
  card: KanbanCard;
  status: string;
  liveApplicationId: number;
  liveEvents?: ActivityEvent[];
  liveVacancyTitle: string | null;
  allEntityFiles: EntityFile[];
}): StageContainer[] {
  const {
    card,
    status,
    liveApplicationId,
    liveEvents,
    liveVacancyTitle,
    allEntityFiles,
  } = params;

  const mergedRaw = Array.isArray(
    (card.extra_data as Record<string, unknown> | undefined)?.merged_from,
  )
    ? ((card.extra_data as Record<string, unknown>)
        .merged_from as Array<Record<string, unknown>>)
    : [];

  const mergedContainers: StageContainer[] = mergedRaw.map((m, i) => {
    const ed = (m.extra_data as Record<string, unknown> | undefined) || {};
    return {
      origin: "merged" as const,
      // Фиктивный (отрицательный) ключ — merged read-only, действий нет.
      applicationId: -(i + 1),
      status: typeof m.status === "string" ? m.status : "new",
      name: typeof m.name === "string" ? m.name : null,
      notes: Array.isArray(ed.notes) ? (ed.notes as ContainerNote[]) : [],
      resumeDemos: Array.isArray(ed.resume_demos)
        ? (ed.resume_demos as ContainerResumeDemo[])
        : [],
      vacancyTitle:
        typeof m.vacancy_title === "string" ? m.vacancy_title : null,
      addedAt: typeof m.added_at === "string" ? m.added_at : undefined,
      fileIds: Array.isArray(m.file_ids) ? (m.file_ids as number[]) : [],
    };
  });

  // Вычитаем из живого все заметки, уже показанные во влитых контейнерах
  // (ключ — id, иначе text+date) — иначе flat-merge их задваивает на «Новом».
  const _noteSig = (n?: ContainerNote) =>
    (n && n.id) || `${n?.text ?? ""}|${n?.date ?? ""}`;
  const _mergedNoteSigs = new Set(
    mergedContainers.flatMap((c) => c.notes.map(_noteSig)),
  );
  const _liveNotes = (
    Array.isArray(card.extra_data?.notes)
      ? (card.extra_data.notes as ContainerNote[])
      : []
  ).filter((n) => !_mergedNoteSigs.has(_noteSig(n)));

  const liveContainer: StageContainer = {
    origin: "live",
    applicationId: liveApplicationId,
    status,
    name: card.name,
    notes: _liveNotes,
    resumeDemos: Array.isArray(card.extra_data?.resume_demos)
      ? (card.extra_data.resume_demos as ContainerResumeDemo[])
      : [],
    vacancyTitle: liveVacancyTitle,
    addedAt: card.created_at,
    events: liveEvents,
  };

  // Файлы по контейнерам: исключаем авто-файлы; merged показывает СВОИ file_ids;
  // живой — остальные (не смёрдженные), т.е. свои собственные документы.
  const _docFiles = (allEntityFiles || []).filter(
    (f) => !isAutoGeneratedFile(f),
  );
  const _mergedFileIds = new Set(
    mergedContainers.flatMap((c) => c.fileIds || []),
  );
  // Один и тот же документ (то же имя+тип) часто прилетает ПОВТОРНО из каждого
  // влитого дубля как отдельная EntityFile-строка — показываем его ОДИН раз, в
  // первом «забравшем» контейнере. Иначе резюме «Иванов.pdf» дублируется N раз
  // (по числу объединений) и в ленте, и в списке «Файлы».
  const _fileSig = (f: EntityFile) =>
    `${f.file_name ?? ""}|${f.file_type ?? ""}|${f.mime_type ?? ""}`;
  const _claimedSigs = new Set<string>();
  const _takeUnique = (files: EntityFile[]) =>
    files.filter((f) => {
      const sig = _fileSig(f);
      if (_claimedSigs.has(sig)) return false;
      _claimedSigs.add(sig);
      return true;
    });
  mergedContainers.forEach((c) => {
    const ids = new Set(c.fileIds || []);
    c.files = _takeUnique(_docFiles.filter((f) => ids.has(f.id)));
  });
  liveContainer.files = _takeUnique(
    _docFiles.filter((f) => !_mergedFileIds.has(f.id)),
  );

  return [liveContainer, ...mergedContainers];
}

// ── Timeline reactions + «Действия» filter (pure) ──

/** Эмодзи-реакция на запись таймлайна (лог карточки). */
export type EntryReaction = {
  emoji: string;
  user_id: number;
  user_name?: string;
  date?: string;
};

/** Полный список фильтров «Действия» (показываются только непустые). */
export const TIMELINE_ACTION_FILTERS = [
  "Сопроводительное письмо",
  "Смена этапа подбора",
  "Комментарий",
  "Письмо кандидату",
  "Интервью",
  "Телефонный звонок",
  "Файл",
  "Оффер",
  "Отказ",
  "Оценка рекрутмента",
];

const getTimelineFilterAliases = (filter: string): string[] => {
  const aliases: Record<string, string[]> = {
    "Смена этапа подбора": ["смен", "этап", "перенес", "новый", "отказ"],
    "Письмо кандидату": ["письм", "email", "почт"],
    "Телефонный звонок": ["телефон", "звон"],
    "Сопроводительное письмо": ["сопровод"],
  };
  return [filter, ...(aliases[filter] || [])].map((value) =>
    value.toLowerCase(),
  );
};

/**
 * Матч записи таймлайна под фильтр «Действия». Комментарий и смена этапа — по
 * ТИПУ записи (kind); остальное (отказ и т.п.) — по тексту (title/body).
 */
export function matchesTimelineFilter(
  item: { title?: string; body?: string; kind?: string },
  filter: string,
): boolean {
  if (filter === "Комментарий") return item.kind === "comment";
  if (filter === "Смена этапа подбора") return item.kind === "stage";
  const aliases = getTimelineFilterAliases(filter);
  const hay = `${item.title || ""} ${item.body || ""}`.toLowerCase();
  return aliases.some((a) => hay.includes(a));
}

// ── System HR tags (авто-метки «HR») ───────────────────────────────────────

/**
 * Авто-метка «HR» — рекрутер, забравший кандидата в активную воронку. Read-only:
 * проставляется бэкендом по created_by активных заявок и хранится в
 * extra_data.system_hr_tags ОТДЕЛЬНО от ручных строковых card.tags, поэтому
 * никогда с ними не конфликтует и не удаляется вручную.
 */
export type SystemHrTag = {
  hr_id: number;
  name: string;
  /** Воронка (вакансия), в которую этот HR забрал кандидата. */
  vacancy_id?: number;
  vacancy_title?: string;
};

/**
 * Достаёт авто-метки HR из extra_data кандидата, отбрасывая мусор (на случай
 * частично заполненного/легаси extra_data). Поля воронки (vacancy_*)
 * опциональны — у легаси-данных их нет, тогда метка показывается без воронки.
 * Порядок сохраняется как пришёл с бэкенда (там он стабилен — по hr_id, vacancy).
 */
export function readSystemHrTags(
  extraData: Record<string, unknown> | undefined | null,
): SystemHrTag[] {
  const raw = extraData?.system_hr_tags;
  if (!Array.isArray(raw)) return [];
  return raw
    .filter(
      (t): t is SystemHrTag =>
        !!t &&
        typeof t === "object" &&
        typeof (t as SystemHrTag).hr_id === "number" &&
        typeof (t as SystemHrTag).name === "string" &&
        (t as SystemHrTag).name.trim().length > 0,
    )
    .map((t) => {
      const tag: SystemHrTag = { hr_id: t.hr_id, name: t.name };
      if (typeof t.vacancy_id === "number") tag.vacancy_id = t.vacancy_id;
      if (typeof t.vacancy_title === "string" && t.vacancy_title.trim()) {
        tag.vacancy_title = t.vacancy_title.trim();
      }
      return tag;
    });
}
